import {test} from 'node:test';import assert from 'node:assert/strict';
import {createMarkdownOptions} from '../src/markdown/pipeline.ts';import {fixtureContent} from './fixtures.ts';
import {pathToFileURL} from 'node:url';import {resolve} from 'node:path';
const filename='mory-asset-01K6F4J0M00000000000000009.png';
async function render(body:string){const content=fixtureContent();content.posts[0].data.imageDimensions={[filename]:{width:1200,height:800}};const o=createMarkdownOptions(content),r=await o.processor.createRenderer(o);return r.render(body,{fileURL:pathToFileURL(resolve(content.posts[0].file)),frontmatter:content.posts[0].data});}
test('caption shares image dimensions, inline Markdown and plain alt fallback; explicit alt wins',async()=>{const a=(await render(`![[${filename}|600]]\n::caption[2026년 **진주 남강** 유등축제]`)).code;assert.match(a,/<figure/);assert.match(a,/width="600" height="400"/);assert.match(a,/alt="2026년 진주 남강 유등축제"/);assert.match(a,/<figcaption>2026년 <strong>진주 남강<\/strong> 유등축제<\/figcaption>/);assert.match(a,/loading="lazy" decoding="async"/);const b=(await render(`![[${filename}]]\n::alt[별도 대체 설명]\n::caption[*caption* [link](https://example.com)]`)).code;assert.match(b,/alt="별도 대체 설명"/);assert.match(b,/width="1200" height="800"/);assert.match(b,/<em>caption<\/em>/);});
test('missing directives mean empty alt; legacy syntax/video/external images still work',async()=>{assert.match((await render(`![[${filename}]]`)).code,/alt=""/);assert.match((await render('![[image.webp|600]]')).code,/width="600"/);assert.match((await render('![[demo.mp4]]')).code,/<video controls/);assert.match((await render('![external](https://example.com/a.png)')).code,/alt="external"/);});
test('image directives report human-readable invalid placement, duplicates and broken brackets; fenced code stays literal',async()=>{for(const body of ['::caption[alone]','::alt[alone]',`![[${filename}]]\n\n::caption[gap]`,`![[${filename}]]\n::alt[a]\n::alt[b]`,`![[${filename}]]\n::caption[a]\n::caption[b]`,`![[${filename}]]\n::caption[broken`])await assert.rejects(render(body),/이미지|alt|caption|빈 줄/);assert.match((await render('```md\n::caption[alone]\n```')).code,/caption/);});
test('caption alt strips HTML and Markdown and escapes attributes; nested bracket links supported',async()=>{const html=(await render(`![[${filename}]]\n::caption[<span>야경</span> **축제** [링크](https://example.com)]`)).code;assert.match(html,/alt="야경 축제 링크"/);assert.doesNotMatch(html,/alt="[^"]*<span/);const escaped=(await render(`![[${filename}]]\n::alt[" & < >]`)).code;assert.match(escaped,/alt="&#x22; &#x26; < >"/);});

test('image line metadata does not consume neighboring prose or a second image',async()=>{const html=(await render(`앞 문장\n![[${filename}]]\n::caption[첫 설명]\n뒤 문장\n![[${filename}]]\n::caption[둘째 설명]\n마지막 문장`)).code;assert.match(html,/앞 문장/);assert.match(html,/뒤 문장/);assert.match(html,/마지막 문장/);assert.equal((html.match(/<figure/g)??[]).length,2);assert.match(html,/첫 설명/);assert.match(html,/둘째 설명/);});
