import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, cpSync, writeFileSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve, join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { Store } from '../server/store.ts';
import { Publisher } from '../server/publish.ts';
import { MoryDeployment, githubActions, suggestCommitMessage } from '../server/deployment.ts';
import { deploymentLabel } from '../deployment.ts';
import type { WorkflowRun } from '../deployment.ts';
import { writeFixtureContent } from '../../tests/fixtures.ts';
import { createApp } from '../server/app.ts';
const git=(cwd:string,args:string[])=>execFileSync('git',args,{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
function fixture(){
 const temp=mkdtempSync(join(tmpdir(),'mory-deployment-')),root=join(temp,'dev'),remote=join(temp,'remote.git'),other=join(temp,'other');mkdirSync(root);
 for(const p of ['src','.gitignore'])cpSync(join(resolve('.'),p),join(root,p),{recursive:true});writeFixtureContent(root);writeFileSync(join(root,'code.ts'),'base\n');
 git(root,['init','-b','main']);git(root,['config','user.name','Test']);git(root,['config','user.email','test@example.invalid']);git(root,['add','.']);git(root,['commit','-m','initial']);git(temp,['clone','--bare',root,remote]);git(root,['remote','add','origin',remote]);git(root,['fetch','origin']);git(temp,['clone',remote,other]);git(other,['config','user.name','Other']);git(other,['config','user.email','other@example.invalid']);
 const store=new Store(root,join(root,'runtime')),publisher=new Publisher(store,{remote,branch:'main',deployment:async()=>({state:'complete'})});
 let conclusion:string|null='success',status='completed',attempt=1,reruns=0,lookups=0,missing=0,apiFailure=false,rerunFailure=false;
 const run=(sha:string):WorkflowRun=>({id:101,sha,name:'Deploy Mory',status,conclusion,url:'https://github.com/test/mory/actions/runs/101',at:'2026-10-02T00:00:00Z',attempt});
 const api={async lookup(sha:string){lookups++;if(apiFailure)throw new Error('secret/raw API error');if(missing-->0)return null;return run(sha);},async rerun(){if(rerunFailure)throw new Error('raw permissions');reruns++;attempt++;status='queued';conclusion=null;}};
 const service=new MoryDeployment(publisher,api,0);
 return {temp,root,remote,other,store,publisher,api,service,git:(a:string[])=>git(root,a),set:(s:string,c:string|null)=>{status=s;conclusion=c;},failAPI:()=>{apiFailure=true;},recoverAPI:()=>{apiFailure=false;},failRerun:()=>{rerunFailure=true;},missing:(n:number)=>{missing=n;},reruns:()=>reruns,lookups:()=>lookups,
  advance(){git(other,['fetch','origin']);git(other,['merge','--ff-only','origin/main']);writeFileSync(join(other,'external.ts'),String(Date.now()));git(other,['add','.']);git(other,['commit','-m','Backup code']);git(other,['push','origin','main']);},close(){store.close();rmSync(temp,{recursive:true,force:true});}};
}
type F=ReturnType<typeof fixture>;
async function execute(f:F,message='user: exact confirmed message'){const s=await f.service.status(true);return f.service.execute({action:s.action,fingerprint:s.fingerprint,message});}
const head=(f:F)=>f.git(['rev-parse','HEAD']);
const count=(f:F)=>f.git(['rev-list','--count','HEAD']);
test('dirty confirmation commits entire intended work with custom message and exact SHA deploy; runtime never staged',async()=>{
 const f=fixture();try{writeFileSync(join(f.root,'code.ts'),'new');writeFileSync(join(f.root,'src/content/pages/about.md'),readFileSync(join(f.root,'src/content/pages/about.md'),'utf8')+'\nlocal');writeFileSync(join(f.store.runtime,'private.txt'),'secret');
 const s=await f.service.status(true);assert.equal(s.action,'commit');assert.equal(s.changed,2);const result=await execute(f);assert.equal(result.action,'none');assert.equal(result.run?.sha,head(f));assert.equal(deploymentLabel(result),'✓ 배포 완료');assert.equal(f.git(['log','-1','--format=%s']),'user: exact confirmed message');assert.equal(git(f.remote,['rev-parse','main']),head(f));assert.equal(f.git(['ls-files','runtime/']),'');
 }finally{f.close();}
});
test('empty message and changed confirmation fingerprint are blocked without commit',async()=>{const f=fixture();try{writeFileSync(join(f.root,'code.ts'),'one');const s=await f.service.status(true);await assert.rejects(f.service.execute({action:'commit',fingerprint:s.fingerprint,message:'   '}),/메시지/);assert.equal(count(f),'1');writeFileSync(join(f.root,'code.ts'),'two');await assert.rejects(f.service.execute({action:'commit',fingerprint:s.fingerprint,message:'x'}),/상태가 변경/);assert.equal(count(f),'1');}finally{f.close();}});
test('commit failure stops before push and preserves files',async()=>{const f=fixture();try{writeFileSync(join(f.root,'code.ts'),'one');const original=f.publisher.dev.git.bind(f.publisher.dev);f.publisher.dev.git=async a=>{if(a[0]==='commit')throw new Error('bad identity');return original(a);};await assert.rejects(execute(f),/커밋하지 못/);assert.equal(count(f),'1');assert.equal(readFileSync(join(f.root,'code.ts'),'utf8'),'one');assert.equal(git(f.remote,['rev-list','--count','main']),'1');}finally{f.close();}});
test('commit then push failure retains commit; retry only pushes without a duplicate commit',async()=>{const f=fixture();try{writeFileSync(join(f.root,'code.ts'),'one');const original=f.publisher.dev.git.bind(f.publisher.dev);let fail=true;f.publisher.dev.git=async a=>{if(a[0]==='push'&&fail)throw new Error('network');return original(a);};await assert.rejects(execute(f),/커밋은 보존/);assert.equal(count(f),'2');const s=await f.service.status(true);assert.equal(s.action,'push');assert.equal(s.ahead,1);fail=false;await execute(f);assert.equal(count(f),'2');assert.equal(git(f.remote,['rev-parse','main']),head(f));}finally{f.close();}});
test('clean local ahead pushes existing commit',async()=>{const f=fixture();try{writeFileSync(join(f.root,'code.ts'),'ahead');f.git(['add','.']);f.git(['commit','-m','Backup local commit']);assert.equal((await f.service.status(true)).action,'push');await execute(f);assert.equal(count(f),'2');}finally{f.close();}});
for(const conclusion of ['failure','cancelled'])test(`equal origin + ${conclusion} reruns same SHA without any Git history change`,async()=>{const f=fixture();try{f.set('completed',conclusion);const sha=head(f);const s=await f.service.status(true);assert.equal(s.action,'rerun');await execute(f);assert.equal(f.reruns(),1);assert.equal(head(f),sha);assert.equal(count(f),'1');f.set('completed','success');assert.equal(deploymentLabel(await f.service.status(true)),'✓ 배포 완료');f.set('completed','failure');assert.equal((await f.service.status(true)).action,'rerun');}finally{f.close();}});
test('equal success is no-op and restarting reconstructs actual Actions state',async()=>{const f=fixture();try{await execute(f);assert.equal(count(f),'1');assert.equal(f.reruns(),0);f.set('in_progress',null);const restarted=new MoryDeployment(f.publisher,f.api);assert.equal(deploymentLabel(await restarted.status(true)),'◌ 배포 중');}finally{f.close();}});
test('remote ahead fast-forwards and preserves partially staged, unstaged and untracked code',async()=>{const f=fixture();try{f.advance();writeFileSync(join(f.root,'code.ts'),'staged');f.git(['add','code.ts']);writeFileSync(join(f.root,'code.ts'),'staged plus unstaged');writeFileSync(join(f.root,'notes'),'untracked');const before=await f.publisher.dev.snapshot();assert.equal((await f.service.status(true)).action,'sync');const after=await execute(f);assert.equal(after.action,'commit');assert.deepEqual(await f.publisher.dev.snapshot(),before);assert.equal(head(f),git(f.remote,['rev-parse','main']));}finally{f.close();}});
test('overlapping incoming work fails safe ff-only without altering local work',async()=>{const f=fixture();try{writeFileSync(join(f.other,'code.ts'),'remote');git(f.other,['add','.']);git(f.other,['commit','-m','remote']);git(f.other,['push']);writeFileSync(join(f.root,'code.ts'),'local');const old=head(f);await assert.rejects(execute(f),/ローカル|ロ|로컬 작업/);assert.equal(head(f),old);assert.equal(readFileSync(join(f.root,'code.ts'),'utf8'),'local');}finally{f.close();}});
test('diverged and wrong branch block automatic deploy',async()=>{const f=fixture();try{f.advance();writeFileSync(join(f.root,'code.ts'),'local');f.git(['add','.']);f.git(['commit','-m','local']);const s=await f.service.status(true);assert.match(s.blocked!,/갈라져/);await assert.rejects(f.service.execute({action:'none',fingerprint:s.fingerprint}),/갈라져/);f.git(['switch','-c','work']);assert.match((await f.service.status(true)).blocked!,/브랜치/);}finally{f.close();}});
for(const marker of ['MERGE_HEAD','CHERRY_PICK_HEAD','REVERT_HEAD','rebase-merge','rebase-apply','BISECT_LOG','index.lock'])test(`${marker} blocks before mutation`,async()=>{const f=fixture();try{writeFileSync(join(f.root,'.git',marker),'marker');assert.match((await f.service.status(true)).blocked!,/작업이 진행/);assert.equal(count(f),'1');}finally{f.close();}});
test('publish and deploy are mutually exclusive without holding Git phase through Actions completion',async()=>{const f=fixture();try{let unlock!:()=>void;const held=f.publisher.deployExclusive(()=>new Promise<void>(r=>unlock=r));await new Promise(r=>setTimeout(r,0));assert.equal((await f.service.status()).busy,true);const draft=f.store.create('post');assert.throws(()=>f.publisher.request(draft.key,draft.revision),/반영하는 중/);await assert.rejects(f.service.execute({action:'none'}),/진행 중/);unlock();await held;
 const job=f.store.db.prepare('INSERT INTO publish_jobs (id,key,revision,action,snapshot,state,started_at,updated_at) VALUES (?,?,?,?,?,?,?,?)');job.run('job',draft.key,1,'publish','{}','publishing','now','now');
 // Enqueue reserves the existing publish queue immediately.
 const original=f.publisher.run.bind(f.publisher);f.publisher.run=async()=>{await new Promise<void>(r=>unlock=r);};f.publisher.enqueue('job');await assert.rejects(f.service.execute({action:'none'}),/진행 중/);await new Promise(r=>setTimeout(r,0));unlock();await f.publisher.idle();f.publisher.run=original;
 }finally{f.close();}});
test('Backup external push and content publication SHA are automatically recognized',async()=>{const f=fixture();try{f.advance();await execute(f);assert.equal((await f.service.status(true)).run?.sha,head(f));const d=f.store.create('post'),saved=f.store.save(d.key,d.revision,{data:{...d.value.data,title:'Content',slug:'content-new'},body:'hello'});const j=f.publisher.request(saved.key,saved.revision);await f.publisher.idle();const pub=f.store.job(j.id);assert.equal(pub.state,'deploying');assert.equal((await f.service.status(true)).run?.sha,pub.commit_sha);}finally{f.close();}});
test('delayed workflow creation polls; no run, queued, in-progress, failure remain distinct',async()=>{const f=fixture();try{writeFileSync(join(f.root,'code.ts'),'new');f.missing(3);await execute(f);assert.ok(f.lookups()>=4);for(const s of ['queued','in_progress']){f.set(s,null);const state=await f.service.status(true);assert.equal(state.run?.status,s);assert.equal(state.action,'none');}f.set('completed','failure');assert.equal((await f.service.status(true)).action,'rerun');f.missing(100);assert.equal((await f.service.status(true)).run,null);}finally{f.close();}});
test('API failures are sanitized, rerun failure leaves Git untouched and remains retryable',async()=>{const f=fixture();try{f.failAPI();assert.match((await f.service.status(true)).githubError!,/상태 확인 실패/);f.recoverAPI();f.set('completed','failure');f.failRerun();const sha=head(f);await assert.rejects(execute(f),/Actions 쓰기 권한/);assert.equal(head(f),sha);assert.equal((await f.service.status(true)).action,'rerun');}finally{f.close();}});
test('push race is rejected normally, preserves local commit and never force pushes',async()=>{const f=fixture();try{writeFileSync(join(f.root,'code.ts'),'new');const original=f.publisher.dev.git.bind(f.publisher.dev);f.publisher.dev.git=async a=>{assert.ok(!a.includes('--force'));if(a[0]==='push')f.advance();return original(a);};await assert.rejects(execute(f),/Push에 실패/);assert.equal(count(f),'2');assert.match((await f.service.status(true)).blocked!,/갈라져/);}finally{f.close();}});
test('GitHub exact SHA and newest attempt matching; prior SHA success does not mask current failure',async()=>{
 let called='';const old={id:12,head_sha:'old',head_branch:'main',event:'push',name:'Pages',status:'completed',conclusion:'success',html_url:'https://github.com/test/mory/actions/runs/12',updated_at:'now',run_attempt:1};
 const current={...old,id:11,head_sha:'current',conclusion:'failure',html_url:'https://github.com/test/mory/actions/runs/11',run_attempt:2};
 const transport=(async(url:any,init:any)=>{called=String(url);if(init?.method==='POST')return new Response(null,{status:201});return Response.json({workflow_runs:[old,{...current,run_attempt:1},current]});}) as typeof fetch;
 const api=githubActions('git@github.com:test/mory.git','server-token','deploy.yml','main',transport);const result=await api.lookup('current');assert.equal(result?.conclusion,'failure');assert.equal(result?.attempt,2);assert.match(called,/head_sha=current/);await api.rerun!(result!);assert.match(called,/runs\/11\/rerun$/);assert.ok(!called.includes('server-token'));assert.equal(await api.lookup('none'),null);
});
test('rule-based message suggestions and state labels',()=>{for(const [paths,message] of [ [['cms/server/assets.ts'],'feat: 이미지 처리 개선'],[['cms/server/backup.ts'],'fix: 백업 및 복구 안정성 개선'],[['cms/client/App.tsx'],'feat: CMS 기능 개선'],[['src/markdown/obsidian.ts'],'feat: 사이트 렌더링 개선'],[['cms/client/style.css'],'style: CMS UI 조정'],[['README.md'],'docs: Mory 문서 업데이트'],[['README.md','cms/server/app.ts'],'chore: Mory 업데이트'] ] as [string[],string][])assert.equal(suggestCommitMessage(paths),message);});
test('same-origin server route protects mutations and confirmation',async()=>{const f=fixture();try{const app=createApp(f.store,f.publisher,'http://cms.test',f.service);const s=await app.request('/api/mory-deployment',{headers:{Host:'cms.test'}});assert.equal(s.status,200);const bad=await app.request('/api/mory-deployment',{method:'POST',headers:{Host:'cms.test','Content-Type':'application/json',Origin:'http://evil.test'},body:'{}'});assert.equal(bad.status,403);assert.equal(count(f),'1');}finally{f.close();}});
test('post-push GitHub failure is only a status error; source commit remains pushed',async()=>{const f=fixture();try{writeFileSync(join(f.root,'code.ts'),'deploy');const original=f.publisher.dev.git.bind(f.publisher.dev);f.publisher.dev.git=async args=>{const result=await original(args);if(args[0]==='push')f.failAPI();return result;};const result=await execute(f);assert.equal(git(f.remote,['rev-parse','main']),head(f));assert.equal(result.ahead,0);assert.match(result.githubError!,/状態|상태 확인/);assert.equal(result.lastError,undefined);}finally{f.close();}});
test('post-push fetch error never claims the push failed',async()=>{const f=fixture();try{writeFileSync(join(f.root,'code.ts'),'deploy');const original=f.publisher.dev.git.bind(f.publisher.dev);let pushed=false;f.publisher.dev.git=async args=>{if(pushed&&args[0]==='fetch')throw new Error('network');const result=await original(args);if(args[0]==='push')pushed=true;return result;};await assert.rejects(execute(f),/Push는 완료/);assert.equal(git(f.remote,['rev-parse','main']),head(f));}finally{f.close();}});
test('another process moving HEAD before push is detected; no unintended commit is pushed',async()=>{const f=fixture();try{writeFileSync(join(f.root,'code.ts'),'ahead');f.git(['add','.']);f.git(['commit','-m','confirmed']);const original=f.publisher.dev.git.bind(f.publisher.dev);let fetches=0;f.publisher.dev.git=async args=>{const result=await original(args);if(args[0]==='fetch'&&++fetches===3){writeFileSync(join(f.root,'second.ts'),'other process');f.git(['add','.']);f.git(['commit','-m','not confirmed']);}return result;};await assert.rejects(execute(f),/로컬 커밋을 변경/);assert.equal(git(f.remote,['rev-list','--count','main']),'1');assert.equal(count(f),'3');}finally{f.close();}});
test('a pending content sync cannot hide a missing publication commit, but normal ahead can be deployed',async()=>{const f=fixture();try{const sha=head(f);f.store.setLocalSync({pending:true,remote_sha:sha,publication_sha:sha,error:'pending',last_attempt_at:'now'});writeFileSync(join(f.root,'code.ts'),'ahead');f.git(['add','.']);f.git(['commit','-m','code']);assert.equal((await f.service.status(true)).action,'push');await execute(f);await f.publisher.retryLocalSync();assert.equal(f.store.localSync()?.pending,false);f.store.setLocalSync({pending:true,remote_sha:head(f),publication_sha:'0000000000000000000000000000000000000000',error:'pending',last_attempt_at:'now'});assert.match((await f.service.status(true)).blocked!,/원격 상태/);}finally{f.close();}});
