import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,readFileSync,rmSync,existsSync,writeFileSync,readdirSync,copyFileSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {fork} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {Readable} from 'node:stream';
import Database from 'better-sqlite3';
import sharp from 'sharp';
import {Store} from '../server/store.ts';
import {Assets} from '../server/assets.ts';
import {ImageMaintenance} from '../server/image-maintenance.ts';
import {backup,restoreStagedAssets} from '../server/backup.ts';
import {lifecycle} from '../server/lifecycle-lock.ts';
import {writeFixtureContent} from '../../tests/fixtures.ts';
import type {RemoteImage,ImageStorage} from '../server/r2.ts';
class Remote implements ImageStorage {
 objects=new Map<string,RemoteImage>();deleted:string[]=[];fail=false;beforeHead?:()=>void;beforeDelete?:()=>void;
 async head(key:string){this.beforeHead?.();return this.objects.get(key)??null;}
 async put(key:string,_file:string,value:RemoteImage){this.objects.set(key,value);}
 async delete(key:string){this.beforeDelete?.();if(this.fail)throw Error('remote unavailable');this.deleted.push(key);this.objects.delete(key);}
}
function setup(){const root=mkdtempSync('/tmp/mory-hardening-');writeFixtureContent(root);const store=new Store(root,join(root,'runtime')),remote=new Remote(),assets=new Assets(store,remote),gc=new ImageMaintenance(assets);return{root,store,assets,remote,gc,close(){store.close();rmSync(root,{recursive:true,force:true});}};}
async function upload(f:ReturnType<typeof setup>,key='page:home') {const b=await sharp({create:{width:20,height:10,channels:3,background:'#224433'}}).png().toBuffer();return f.assets.upload(key,Readable.toWeb(Readable.from([b])) as any,'photo.png');}
const save=(f:ReturnType<typeof setup>,body:string,key='page:home')=>{const r=f.store.get(key);return f.store.save(key,r.revision,{...r.value,body});};
const day=(n:number)=>new Date(Date.UTC(2026,9,n,12));
async function child(f:ReturnType<typeof setup>,mode:string){const p=fork(fileURLToPath(new URL('./fixtures/lifecycle-worker.ts',import.meta.url)),[f.root,mode],{execArgv:['--import',resolve('node_modules/tsx/dist/loader.mjs')],stdio:['ignore','ignore','inherit','ipc']});await new Promise<void>((r,j)=>{p.once('message',()=>r());p.once('error',j);p.once('exit',code=>{if(code)j(Error('worker failed'));});});return p;}
const ended=(p:ReturnType<typeof fork>)=>new Promise<void>(r=>p.once('exit',()=>r()));
for(const mode of ['backup','automatic'])test(`${mode} in another process blocks destructive image cleanup and saves matching blobs`,async()=>{const f=setup();try{const a=await upload(f),asset=f.assets.get(a.id)!;const p=await child(f,mode);const done=ended(p);f.store.db.prepare("UPDATE assets SET r2_uploaded_at='x',published_at='x' WHERE id=?").run(a.id);f.assets.cleanup();assert(existsSync(f.assets.path(asset)));p.send('release');await done;f.assets.cleanup();assert(!existsSync(f.assets.path(asset)));const files=readdirSync(join(f.store.runtime,'backups')).filter(n=>n.endsWith('.sqlite'));assert.equal(files.length,1);const db=new Database(join(f.store.runtime,'backups',files[0]),{readonly:true});assert(db.prepare('SELECT id FROM assets WHERE id=?').get(a.id));db.close();assert(existsSync(join(f.store.runtime,'backups/assets',asset.sha256)));}finally{f.close();}});
test('backup waits for cleanup in a different process',async()=>{const f=setup();try{const a=await upload(f);f.store.db.prepare("UPDATE assets SET r2_uploaded_at='x',published_at='x' WHERE id=?").run(a.id);const p=await child(f,'cleanup');assert.equal(f.assets.get(a.id)!.local_path,null);let finished=false;const pending=backup(f.store,day(2),{manual:true}).then(()=>finished=true);await new Promise(r=>setTimeout(r,100));assert.equal(finished,false);const done=ended(p);p.send('release');await done;await pending;assert(finished);}finally{f.close();}});
for(const mode of ['backup','cleanup'])test(`${mode} process crash releases lock; next backup succeeds`,async()=>{const f=setup();try{const p=await child(f,mode),done=ended(p);p.kill('SIGKILL');await done;assert(existsSync(await backup(f.store,day(2),{manual:true})));}finally{f.close();}});
test('every manual backup is fresh on same day; restore preserves latest draft and hash-deduplicated staged binary',async()=>{const f=setup();try{const a=await upload(f),asset=f.assets.get(a.id)!;save(f,'first');const first=await backup(f.store,day(2),{manual:true});save(f,`latest\n![[${a.filename}]]`);const second=await backup(f.store,day(2),{manual:true});assert.notEqual(first,second);const db=new Database(second,{readonly:true});const row:any=db.prepare("SELECT value FROM drafts WHERE key='page:home'").get();assert.match(JSON.parse(row.value).body,/latest/);assert.equal(db.pragma('quick_check',{simple:true}),'ok');db.close();assert.equal(readdirSync(join(f.store.runtime,'backups/assets')).length,1);rmSync(f.assets.path(asset));restoreStagedAssets(f.store);assert(existsSync(f.assets.path(asset)));}finally{f.close();}});
test('staged grace resets when referenced, and only continuously unused assets are removed after seven days',async()=>{const f=setup();try{const a=await upload(f);await f.gc.gc(day(2));assert(f.assets.get(a.id)!.staged_orphaned_at);save(f,`![[${a.filename}]]`);assert.equal(f.assets.get(a.id)!.staged_orphaned_at,null);await f.gc.gc(day(12));assert(f.assets.get(a.id)!.local_path);save(f,'unused again');await f.gc.gc(day(13));await f.gc.gc(day(19));assert(f.assets.get(a.id)!.local_path);await f.gc.gc(day(20));assert.equal(f.assets.get(a.id)!.local_path,null);assert(f.assets.get(a.id)!.local_deleted_at);}finally{f.close();}});
test('R2 grace, DELETE failure retry, hash mismatch, and final reference rescan are conservative',async()=>{const f=setup();try{const a=await upload(f);save(f,`![[${a.filename}]]`);await f.assets.prepare(f.store.get('page:home'),f.store.get('page:home').value,f.root);save(f,'unused');await f.gc.gc(day(2));await f.gc.gc(day(31));assert.equal(f.remote.deleted.length,0);f.remote.fail=true;await f.gc.gc(day(33));assert.equal(f.assets.get(a.id)!.r2_deleted_at,null);f.remote.fail=false;f.remote.beforeHead=()=>{f.remote.beforeHead=undefined;save(f,`![[${a.filename}]]`);};await f.gc.gc(day(34));assert.equal(f.remote.deleted.length,0);assert.equal(f.assets.get(a.id)!.r2_orphaned_at,null);save(f,'unused');await f.gc.gc(day(35));const asset=f.assets.get(a.id)!;f.remote.objects.get(asset.r2_key)!.sha256='0'.repeat(64);await f.gc.gc(day(66));assert.equal(f.remote.deleted.length,0);f.remote.objects.get(asset.r2_key)!.sha256=asset.sha256;await f.gc.gc(day(67));assert.equal(f.remote.deleted.length,1);assert(f.assets.get(a.id)!.r2_deleted_at);}finally{f.close();}});
test('published/archived snapshots and failed pinned jobs protect images; integrity warns without changing Markdown',async()=>{const f=setup();try{const post=f.store.list().find(d=>d.kind==='post')!,a=await upload(f,post.key);save(f,`![[${a.filename}]]`,post.key);const row=f.store.get(post.key);await f.assets.prepare(row,row.value,f.root);f.store.db.prepare('UPDATE drafts SET published=?,value=? WHERE key=?').run(JSON.stringify(row.value),JSON.stringify({...row.value,body:'draft without old image',data:{...row.value.data,status:'archived'}}),row.key);await f.gc.gc(day(2));await f.gc.gc(day(66));assert.equal(f.remote.deleted.length,0);const oldBody=f.store.get(row.key).published!.body;f.remote.objects.clear();const check=await f.gc.integrity();assert(check.errors>0);assert.equal(f.store.get(row.key).published!.body,oldBody);const b=await upload(f);const current=f.store.get('page:home');f.store.db.prepare('INSERT INTO publish_jobs (id,key,revision,action,snapshot,state,started_at,updated_at) VALUES (?,?,?,?,?,?,?,?)').run('pinned','page:home',current.revision,'publish',JSON.stringify({...current.value,body:`![[${b.filename}]]`}), 'failed','x','x');await f.gc.gc(day(66));assert.equal(f.assets.get(b.id)!.staged_orphaned_at,null);}finally{f.close();}});
test('malformed reference anywhere defers GC rather than deleting ambiguous assets',async()=>{const f=setup();try{const a=await upload(f);await f.gc.gc(day(2));save(f,'::caption[not attached]');const result=await f.gc.gc(day(99));assert(result.errors);assert(f.assets.get(a.id)!.local_path);}finally{f.close();}});
test('CMS preview/public image structure and captions are identical',async()=>{const f=setup();try{const {renderPreview}=await import('../server/preview.ts'),{createMarkdownOptions}=await import('../../src/markdown/pipeline.ts'),{readContent}=await import('../../src/lib/content.ts'),{pathToFileURL}=await import('node:url');const a=await upload(f),payload={...f.store.get('page:home').value,body:`![[${a.filename}|600]]\n::alt[사진 설명]\n::caption[**축제** 야경]`,data:{...f.store.get('page:home').value.data,imageDimensions:{[a.filename]:{width:20,height:10}}}};const preview=await renderPreview(f.store,'page:home',payload,'light');const content=readContent(f.root);content.pages.find(p=>p.key==='home')!.data.imageDimensions=payload.data.imageDimensions;const o=createMarkdownOptions(content),renderer=await o.processor.createRenderer(o),html=(await renderer.render(payload.body,{fileURL:pathToFileURL(join(f.root,'src/content/pages/home.md')),frontmatter:payload.data})).code;for(const source of [preview,html]){assert.match(source,/<figure/);assert.match(source,/width="600" height="300"/);assert.match(source,/alt="사진 설명"/);assert.match(source,/<figcaption><strong>축제<\/strong> 야경<\/figcaption>/);}assert.match(preview,/<figure[^>]*data-source-start="1"/);assert.match(preview,new RegExp(`/api/assets/${a.id}/content`));assert.match(html,/https:\/\/img.mory.place\/pages\/home/);}finally{f.close();}});
test('permanent delete leaves orphan metadata; detached final file is collected only after grace',async()=>{const f=setup();try{const a=await upload(f),asset=f.assets.get(a.id)!;f.store.db.prepare('DELETE FROM assets WHERE id=?').run(a.id);await f.gc.gc(day(2));assert(existsSync(f.assets.path(asset)));await f.gc.gc(day(9));assert(!existsSync(f.assets.path(asset)));}finally{f.close();}});

test('restore simulation reopens backed-up SQLite and recovers staged binary from matching blob',async()=>{const f=setup();let restored:Store|undefined;try{const a=await upload(f),asset=f.assets.get(a.id)!;save(f,`saved before backup\n![[${a.filename}]]`);const snapshot=await backup(f.store,day(2),{manual:true});save(f,'later work');f.store.close();rmSync(f.assets.path(asset));copyFileSync(snapshot,join(f.store.runtime,'cms.sqlite'));restored=new Store(f.root,f.store.runtime);restoreStagedAssets(restored);assert.match(restored.get('page:home').value.body,/saved before backup/);assert(existsSync(join(f.store.runtime,asset.local_path!)));assert.equal(restored.db.pragma('quick_check',{simple:true}),'ok');}finally{restored?.close();f.close();}});
test('new uploads record original and public byte sizes without resizing',async()=>{const f=setup();try{const a=await upload(f),row:any=f.store.db.prepare('SELECT * FROM assets WHERE id=?').get(a.id);assert(row.original_size_bytes>0);assert.equal(row.width,20);assert.equal(row.height,10);assert(row.size_bytes<=row.original_size_bytes);}finally{f.close();}});

test('invalid orphan timestamps never bypass grace and never authorize a delete',async()=>{const f=setup();try{const a=await upload(f);f.store.db.prepare("UPDATE assets SET staged_orphaned_at='invalid'").run();await f.gc.gc(day(99));assert(f.assets.get(a.id)!.local_path);save(f,`![[${a.filename}]]`);await f.assets.prepare(f.store.get('page:home'),f.store.get('page:home').value,f.root);save(f,'unused');f.store.db.prepare("UPDATE assets SET r2_orphaned_at='0'").run();await f.gc.gc(day(99));assert.equal(f.remote.deleted.length,0);assert.equal(f.assets.get(a.id)!.r2_deleted_at,null);}finally{f.close();}});

test('ordinary Markdown/HTML public managed-image URLs are GC-protected and audited using shared parsing',async()=>{const f=setup();try{const a=await upload(f);save(f,`![[${a.filename}]]`);await f.assets.prepare(f.store.get('page:home'),f.store.get('page:home').value,f.root);const asset=f.assets.get(a.id)!,body=`![photo](https://img.mory.place/${asset.r2_key})\n\n<img src="https://img.mory.place/${asset.r2_key}" alt="photo">`;const row=save(f,body);f.store.db.prepare('UPDATE drafts SET published=? WHERE key=?').run(JSON.stringify(row.value),row.key);await f.gc.gc(day(2));await f.gc.gc(day(99));assert.equal(f.remote.deleted.length,0);f.remote.objects.clear();assert.equal((await f.gc.integrity()).errors,1);}finally{f.close();}});

test('corrupt ownership/path metadata cannot authorize deleting a different object or file',async()=>{const f=setup();try{const a=await upload(f);f.store.db.prepare("UPDATE assets SET r2_uploaded_at='x',r2_orphaned_at='2020-01-01T00:00:00Z',r2_key='foreign/object.png' WHERE id=?").run(a.id);const result=await f.gc.gc(day(99));assert(result.errors);assert.equal(f.remote.deleted.length,0);assert(f.assets.get(a.id)!.local_path);}finally{f.close();}});
