import { Component, useEffect, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { api } from './api.ts';
import type { AnalyticsTab } from './navigation.ts';
type AnalyticsNavigation = { tab: AnalyticsTab; navigate: (tab: AnalyticsTab) => void };
const time=(value:number|null|undefined)=>value?new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',dateStyle:'medium',timeStyle:'short'}).format(value*1000):'—';
const number=(value:number|null|undefined)=>value==null?'—':value.toLocaleString('ko-KR');
function Table({headers,rows}:{headers:string[];rows:any[][]}){return <div className="analytics-table-wrap"><table><thead><tr>{headers.map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>):<tr><td colSpan={headers.length}>아직 기록이 없습니다.</td></tr>}</tbody></table></div>;}
class AnalyticsBoundary extends Component<{children:ReactNode},{failed:boolean}> {
 state={failed:false};
 static getDerivedStateFromError(){return{failed:true};}
 render(){return this.state.failed?<section><h1>방문 통계</h1><p role="alert">통계 화면을 표시하지 못했습니다. 글 작성과 게시 기능은 계속 사용할 수 있습니다.</p><button onClick={()=>this.setState({failed:false})}>다시 불러오기</button></section>:this.props.children;}
}
export default function AnalyticsPanel(props: AnalyticsNavigation){return <AnalyticsBoundary><Analytics {...props}/></AnalyticsBoundary>;}
function Analytics({tab: routeTab,navigate}: AnalyticsNavigation){
 const [tab,setTab]=useState<AnalyticsTab>(routeTab),[period,setPeriod]=useState('30'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[query,setQuery]=useState(''),[offset,setOffset]=useState(0);
 const [data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[storage,setStorage]=useState<any>(null);
 const [visitor,setVisitor]=useState<any>(null),[nickname,setNickname]=useState(''),[writing,setWriting]=useState(false),[notice,setNotice]=useState('');
 const [syncing,setSyncing]=useState(false);const sequence=useRef(0);
 useEffect(()=>{if(routeTab===tab)return;sequence.current++;setData(null);setBusy(true);setVisitor(null);setNotice('');setTab(routeTab);setOffset(0);},[routeTab,tab]);
 useEffect(()=>{
  if(period==='custom'&&(!from||!to))return;
  const id=++sequence.current;setBusy(true);setError('');setData(null);
  const params=new URLSearchParams({period,from,to,query,offset:String(offset)});
  const timer=setTimeout(()=>{void api(`/api/analytics/${tab}?${params}`).then(next=>{if(id===sequence.current)setData(next);}).catch(e=>{if(id===sequence.current)setError(e.message);}).finally(()=>{if(id===sequence.current)setBusy(false);});},tab==='visitors'?250:0);
  return()=>{clearTimeout(timer);sequence.current++;};
 },[tab,period,from,to,query,offset,refresh]);
 function open(id:number){const request=++sequence.current;setBusy(true);setError('');void api<any>(`/api/analytics/visitors/${id}`).then(next=>{if(request===sequence.current){setVisitor(next);setNickname(next.visitor.nickname??'');}}).catch(e=>{if(request===sequence.current)setError(e.message);}).finally(()=>{if(request===sequence.current)setBusy(false);});}
 function switchTab(next:AnalyticsTab){navigate(next);}
 const labels={overview:'개요',visitors:'방문자',pages:'페이지',search:'검색'};
 return <section className="analytics" aria-label="방문 통계"><div className="section-heading"><h1>방문 통계</h1><button onClick={()=>setRefresh(x=>x+1)} disabled={busy}>새로고침</button></div>
  <nav className="analytics-tabs" aria-label="통계 화면">{Object.entries(labels).map(([id,label])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>switchTab(id as AnalyticsTab)}>{label}</button>)}</nav>
  {!visitor&&<div className="filters"><label>기간 <select aria-label="통계 기간" value={period} onChange={e=>{setPeriod(e.target.value);setOffset(0);}}><option value="1">오늘</option><option value="7">7일</option><option value="30">30일</option><option value="365">1년</option><option value="all">전체</option><option value="custom">직접 선택</option></select></label>{period==='custom'&&<><label>시작일 <input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>종료일 <input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></>}</div>}
  {error&&<p role="alert">! {error} <button onClick={()=>setRefresh(x=>x+1)}>다시 확인</button></p>}
  {notice&&<p role="status">{notice}</p>}{busy&&<p role="status">통계를 불러오는 중…</p>}
  {visitor?<><button onClick={()=>{sequence.current++;setVisitor(null);setRefresh(x=>x+1);}}>← 방문자 목록</button><h2>{visitor.visitor.nickname||visitor.visitor.visitor_key.slice(0,8)+'…'}</h2><form className="analytics-nickname" onSubmit={e=>{e.preventDefault();const request=sequence.current;setWriting(true);setError('');void api<any>(`/api/analytics/visitors/${visitor.visitor.id}/nickname`,'PUT',{nickname}).then(next=>{if(request===sequence.current){setVisitor(next);setRefresh(x=>x+1);setNotice('별칭을 저장했습니다.');}}).catch(e=>{if(request===sequence.current)setError(e.message);}).finally(()=>setWriting(false));}}><label>별칭 <input value={nickname} maxLength={80} onChange={e=>setNickname(e.target.value)}/></label><button disabled={writing}>{writing?'저장 중…':'별칭 저장'}</button><span className="muted">빈칸으로 저장하면 별칭을 지웁니다.</span></form>
   <dl className="analytics-summary"><div><dt>최초 방문</dt><dd>{time(visitor.visitor.first_seen_at)}</dd></div><div><dt>최근 방문</dt><dd>{time(visitor.visitor.last_seen_at)}</dd></div><div><dt>누적 방문</dt><dd>{number(visitor.visitor.total_visits)}</dd></div><div><dt>누적 페이지뷰</dt><dd>{number(visitor.visitor.total_pageviews)}</dd></div></dl>
   <h3>최근 방문 기록</h3><p className="muted">상세 기록은 최근 365일만 남습니다. 이전 방문의 누적 통계와 별칭은 유지됩니다.</p>
   <Timeline rows={visitor.timeline}/>{visitor.next!=null&&<button onClick={()=>{const request=sequence.current;setBusy(true);void api<any>(`/api/analytics/visitors/${visitor.visitor.id}?offset=${visitor.next}`).then(next=>{if(request===sequence.current)setVisitor({...next,timeline:[...visitor.timeline,...next.timeline]});}).catch(e=>{if(request===sequence.current)setError(e.message);}).finally(()=>{if(request===sequence.current)setBusy(false);});}} disabled={busy}>이전 기록 더 보기</button>}
  </>:data&&<>
  {tab==='overview'&&<><dl className="analytics-summary">{[['방문자',data.totals.visitors],['방문',data.totals.visits],['페이지뷰',data.totals.pageviews],['신규 방문자',data.totals.new_visitors],['재방문자',data.totals.returning_visitors]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{number(value)}</dd></div>)}</dl>{!data.exactUnique&&<p className="muted">365일 이전을 포함한 직접 선택 기간의 고유 방문자 수는 상세 기록 만료로 제공하지 않습니다. 전체 기간 고유 방문자 수는 누적 방문자 기준입니다.</p>}
   <h2>일별 방문</h2><Trend rows={data.trend}/><details><summary>일별 숫자 보기</summary><Table headers={['날짜','조회','방문자','방문','신규','재방문']} rows={data.trend.map((r:any)=>[r.date,number(r.pageviews),number(r.unique_visitors),number(r.visits),number(r.new_visitors),number(r.returning_visitors)])}/></details>
   <h2>많이 본 페이지</h2><Table headers={['페이지','조회']} rows={data.topPages.map((p:any)=>[p.canonical_path,number(p.period_pageviews)])}/><h2>유입</h2><Table headers={['호스트','유형','도착','조회']} rows={data.sources.map((r:any)=>[r.host||'직접 방문',r.source_type,number(r.landings),number(r.pageviews)])}/><h2>국가·기기</h2><Table headers={['구분','값','조회']} rows={data.breakdowns.filter((r:any)=>['country','device'].includes(r.dimension)).map((r:any)=>[r.dimension,r.value,number(r.pageviews)])}/><details><summary>브라우저·OS</summary><Table headers={['구분','값','조회']} rows={data.breakdowns.filter((r:any)=>['browser','os'].includes(r.dimension)).map((r:any)=>[r.dimension,r.value,number(r.pageviews)])}/></details>
  </>}
  {tab==='visitors'&&<><p className="muted">방문자 목록은 기간과 관계없이 누적 요약을 표시합니다.</p><label className="analytics-search">방문자 검색 <input type="search" enterKeyHint="search" placeholder="별칭 또는 식별자 앞부분" value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);}} onKeyDown={e=>{if(e.key==='Enter'&&!e.nativeEvent.isComposing)e.currentTarget.blur();}}/></label><ul className="analytics-visitors">{data.visitors.map((v:any)=><li key={v.id}><button onClick={()=>open(v.id)}><strong>{v.nickname||v.visitor_key.slice(0,8)+'…'}</strong><span>{v.total_visits>1?'재방문':'신규'} · 방문 {number(v.total_visits)} · 조회 {number(v.total_pageviews)}</span><span>최초 {time(v.first_seen_at)} · 최근 {time(v.last_seen_at)}</span></button></li>)}</ul>{!data.visitors.length&&<p>방문자 기록이 없습니다.</p>}<div className="analytics-pagination">{offset>0&&<button onClick={()=>setOffset(Math.max(0,offset-50))}>이전</button>}{data.next!=null&&<button onClick={()=>setOffset(data.next)}>다음</button>}</div></>}
  {tab==='pages'&&<><Table headers={['페이지','유형','기간 조회','누적 조회','최초','최근']} rows={data.pages.map((p:any)=>[p.canonical_path,p.route_type,number(p.period_pageviews),number(p.total_pageviews),time(p.first_view_at),time(p.last_view_at)])}/><h2>찾을 수 없었던 주소 · 404</h2><Table headers={['주소','기간 조회','누적 조회']} rows={data.notFound.map((p:any)=>[p.path,number(p.period_pageviews),number(p.total_pageviews)])}/></>}
  {tab==='search'&&<><h2>Mory 내부 검색</h2><Table headers={['검색어','검색','결과 없음','클릭','최근']} rows={data.internal.map((r:any)=>[r.normalized_query,number(r.total_searches),number(r.zero_result_count),number(r.total_clicks),time(r.last_seen_at)])}/><details><summary>최근 상세 검색 · 365일</summary><Table headers={['시각','방문자','검색어','결과']} rows={data.raw.map((r:any)=>[time(r.occurred_at),<button onClick={()=>open(r.visitor_id)}>{r.visitor}</button>,r.query,number(r.result_count)])}/></details>
   <h2>Google 외부 검색</h2><p className="muted">Search Console 집계는 개인 방문자와 연결하지 않습니다. Google의 개인정보 보호·집계 정책에 따라 일부 검색어는 제공되지 않습니다. 날짜는 Search Console 기준입니다. 동기화는 3일 전부터 30일 전까지 확정 데이터(28일)를 갱신합니다.</p><p>마지막 동기화: {time(data.lastSync)}</p><button disabled={syncing||!data.googleConfigured} onClick={()=>{setSyncing(true);setError('');void api<any>('/api/analytics/google/sync','POST',{}).then(r=>{setNotice(`Google 검색 통계 ${r.imported}행을 동기화했습니다.`);setRefresh(x=>x+1);}).catch(e=>setError(e.message)).finally(()=>setSyncing(false));}}>{syncing?'동기화 중…':'Google 검색 통계 동기화'}</button>{!data.googleConfigured&&<p className="muted">서버에 Google 서비스 계정을 설정한 뒤 동기화할 수 있습니다.</p>}<Table headers={['검색어','도착 페이지','클릭','노출','CTR','평균 순위']} rows={data.external.map((r:any)=>[r.query,r.landing_page,number(r.clicks),number(r.impressions),`${(r.ctr*100).toFixed(1)}%`,r.position.toFixed(1)])}/><h2>Naver</h2><p className="muted">Naver 검색 유입과 도착 페이지를 기록합니다. 검색어 통계 조회를 위한 공식 API를 확인하지 못해 외부 검색어 상세 연동은 지원하지 않습니다.</p></>}
  </>}
  <details className="analytics-storage"><summary>D1 저장 상태</summary><button onClick={()=>{setError('');void api('/api/analytics/storage').then(setStorage).catch(e=>setError(e.message));}}>DB 상태 확인</button>{storage&&<><p role="status">{storage.level==='strong'?'! 저장 용량 매우 부족':storage.level==='warning'?'! 저장 용량 경고':storage.level==='notice'?'! 저장 용량 주의':'저장 상태'} · {storage.sizeBytes==null?'용량 정보 없음':`${(storage.sizeBytes/1000000).toFixed(1)} / 500 MB`}</p><p>원본 방문 {number(storage.pageviews)} · 검색 {number(storage.searches)} · 클릭 {number(storage.clicks)} · 방문자 {number(storage.visitors)}</p><p>가장 오래된 기록 {time(storage.oldest_raw)} · 상세 보관 365일</p><p>최근 30일 방문 {number(storage.recent_pageviews)} · 용량 변화 {storage.sizeGrowth30Days==null?'측정 대기':`${(storage.sizeGrowth30Days/1000000).toFixed(1)} MB`}</p></>}</details>
 </section>;
}
function Trend({rows}:{rows:any[]}){if(!rows.length)return <p>아직 기록이 없습니다.</p>;const max=Math.max(1,...rows.map(r=>r.pageviews));return <svg className="analytics-trend" viewBox="0 0 600 140" role="img" aria-label="일별 페이지뷰 추이"><title>일별 페이지뷰 추이</title>{rows.map((r,i)=><rect key={r.date} x={i*600/rows.length} y={130-r.pageviews/max*120} width={Math.max(.3,600/rows.length-1)} height={r.pageviews/max*120} fill="currentColor"><title>{r.date}: {r.pageviews} 조회</title></rect>)}</svg>;}
function Timeline({rows}:{rows:any[]}){
 if(!rows.length)return <p>최근 365일 상세 기록이 없습니다.</p>;
 const groups:any[][]=[];for(const row of [...rows].reverse()){if(!groups.length||(row.type==='pageview'&&row.is_visit))groups.push([]);groups.at(-1)!.push(row);}
 return <div>{groups.reverse().map((group,i)=><section className="analytics-visit" key={i}><h4>{time(group[0].occurred_at)} · 방문</h4><ol>{group.map((r:any,j:number)=><li key={`${r.type}:${r.id}:${j}`}><time>{time(r.occurred_at)}</time><span>{r.type==='search'?`검색 “${r.query}” · 결과 ${r.result_count}`:r.type==='search_click'?`“${r.query}” ${r.rank}번째 결과 클릭 · ${r.path}`:r.path}</span>{r.type==='pageview'&&<small>{r.host||'직접 방문'} · {r.source_type}</small>}</li>)}</ol></section>)}</div>;
}
